### ISSUE TITLE
Multiple Vuejs Applications

### ISSUE THREAD

**Issue by EvanBurbidge** [slanatech/vue-monorepo-boilerplate#3]
Hi first of all great work.

I'm working ona project at the moment and would like to pick your brains a bit.
If we have two apps, app1, app2. Both with their own stores and vuejs router configurations, would this be a good approach to take with them? If so how would you go about installing app2 into app1 and allowing the routers to "merge" into one overall application router? 

One thing i've tried is simply exporting a router configuration from each part of these and installing it all in app one but then webpack complains to me that it cannot find the components of app2.

**Comment by MikeJones7** [comment]
Hi Evan,
Did you find a solution to this problem? We're struggling with a similar issue.
Cheers

**Comment by EvanBurbidge** [comment]
hi @MikeJones7  so in one way yes, in another no, what we do is just import the src files and allow the "consuming" application to manage all of the dependencies, we're also now exploring the single-spa meta framework in order to have individual applications, they put a nice Pr up yesterday demonstrating code splitting so its quite nice to use.
