### ISSUE TITLE
Add Quasar to Vue help

### ISSUE THREAD

**Issue by corepay** [slanatech/vue-monorepo-boilerplate#5]
Hi I really want to use this as a base for a current project and more down the road.  I have spent 2 days now trying to reason babel and know now why they named it babel.

From a fresh build I add `vue add quasar` to the ui.  This results in import errors to the Quasar packages.  I think I see the issue has to do with babel ignoring packages (more specifically `babel-plugin-transform-imports` in the UI folder - but hell I don't know.  Am new to this monorepo magic.  What I am finding at University of Google is a lot of confusion, some saying to upgrade to babel 7 others saying that babel 7 has a lot of problems...some solutions that include 77 or so new babel config files and some code snippets with no indication WHERER they should be placed. 

Do you have any ideas how this would work?  Asking a lot but would be very appreciated.  All you need to do is a fresh install of your package and `vue add quasar` in `ui` and you will see the errors right after bootstrap and try `yarn run dev`

**Comment by sv2** [comment]
From the top of my head - probably would suggest to upgrade boilerplate to the latest vue-cli first ( 3.8.4 ) . This was created using 3.0 beta vue-cli quite some time ago ... 
Try cloning boilerplate, changing UI package.json to use vue-cli 3.8.4, and then try `vue add quasar`

**Comment by corepay** [comment]
Hi and thanks for reply.  Yes I did upgrade all packages to their highest major release - tested all builds and docker just fine (you can update this repo easy - 10 minutes).  Further investigation shows this has something to do with babel calling the quasar modules (and maybe eslint also) needing to be in the workspace root.

I am still digging in trying to sort through all this complexity and learn the concepts of a workspace - just hoping it was something common or simple I was failing to address.  

Thanks again - you can close this issue, it has nothing to do with any bugs.

- Best

**Comment by corepay** [comment]
Oh one thing if you upgrade all the packages.  In ui upgrade the eslint to the next major release ->  `"@vue/eslint-config-standard": "^4.0.0”`  then you need to move the `.eslintrc` to the root folder.

Cheers

**Comment by corepay** [comment]
HI, not going workspaces any longer, might try it again next big project but was too complex with tight deadline.  Closing to clean up issues....
